#source 'https://github.com/CocoaPods/Specs.git'
source 'git@gitlab.alibaba-inc.com:alipods/specs-mirror.git'

platform :ios, '7.0'

xcodeproj 'XinranReadingGroup'

pod 'AFNetworking','2.5.2'
pod 'JSONModel', '~> 1.1.0'
pod 'SSKeychain','1.2.2'
pod 'SDWebImage','3.7.1'
pod 'BlocksKit','2.2.5'
pod 'MBProgressHUD','0.9.1'

#pod 'ZYCoreFramework',:git=>'git@bitbucket.org:yun_zeng/zycoreframework.git'
pod 'ZYCoreFramework',:path=>'~/Developer/Code/Mine/iOS/ZYCoreFramework'
#pod 'ZYCoreFramework',:path=>'~/Developer/Zeng Yun/zycoreframework'