source 'git@github.com:CocoaPods/Specs.git'
platform :ios, '8.0'

#use_frameworks!

target 'XinranReadingGroup' do
    pod 'AFNetworking','2.6.0'
    pod 'JSONModel', '~> 1.1.0'
    pod 'SSKeychain','1.2.2'
    pod 'SDWebImage','3.7.1'
    pod 'BlocksKit','2.2.5'
    pod 'SVProgressHUD'
    pod 'Masonry','0.6.3'
    pod 'OAStackView','0.1.0'
    pod 'FDStackView','1.0-alpha'
    pod 'CocoaLumberjack','2.2.0'
    pod 'DZNEmptyDataSet'
    pod 'Mantle'
    pod 'PINCache'
    pod 'UMengFeedback', '~> 2.3.4'
    pod 'TZImagePickerController'
    pod 'Fabric'
    pod 'Crashlytics'
    
    pod 'ZYCoreFramework',:git=>'git@github.com:zengyun-programmer/ZYCoreFramework.git',:tag=>'0.1'
    pod 'DUQRAssistant',:git=>'git@github.com:zengyun-programmer/DUQRAssistant.git',:branch=>'develop'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
        end
    end
end
