source 'git@github.com:CocoaPods/Specs.git'

platform :ios, '7.0'

xcodeproj 'XinranReadingGroup'

pod 'AFNetworking','2.6.0'
pod 'JSONModel', '~> 1.1.0'
pod 'SSKeychain','1.2.2'
pod 'SDWebImage','3.7.1'
pod 'BlocksKit','2.2.5'
pod 'SVProgressHUD'
pod 'Masonry','0.6.3'
pod 'Reveal-iOS-SDK', :configurations => ['Debug']
pod 'OAStackView','0.1.0'
pod 'Bugtags'
pod 'FDStackView','1.0-alpha'
pod 'CocoaLumberjack'
pod 'DZNEmptyDataSet'
pod 'Mantle'
pod 'PINCache'

#pod 'ZYCoreFramework',:git=>'git@bitbucket.org:yun_zeng/zycoreframework.git'
pod 'ZYCoreFramework',:path=>'~/Developer/Code/Mine/iOS/ZYCoreFramework'
#pod 'ZYCoreFramework',:path=>'~/Developer/Zeng Yun/zycoreframework'
pod 'DUQRAssistant',:path=>'~/Developer/code/mine/ios/DUQRAssistant'